// Code generated by cmd/connect-registration from generated/service-catalog.json and connect_bindings.yaml. DO NOT EDIT.

package adapters

import (
	"net/http"

	"connectrpc.com/connect"

	genconnect "accounts/pkg/gen/saas/accounts/v1/accountsv1connect"
)

// Compile-time assertions keep every configured adapter aligned with the
// descriptor-generated Connect handler interface.
var (
	_ genconnect.APIKeyServiceHandler             = (*apiKeyConnectHandler)(nil)
	_ genconnect.AccessibleScopeServiceHandler    = (*accessibleScopeConnectHandler)(nil)
	_ genconnect.AuditServiceHandler              = (*auditConnectHandler)(nil)
	_ genconnect.AuthServiceHandler               = (*authConnectHandler)(nil)
	_ genconnect.BillingServiceHandler            = (*billingConnectHandler)(nil)
	_ genconnect.ConsentServiceHandler            = (*consentConnectHandler)(nil)
	_ genconnect.DashboardServiceHandler          = (*dashboardConnectHandler)(nil)
	_ genconnect.DatasourceServiceHandler         = (*datasourceConnectHandler)(nil)
	_ genconnect.DelegationServiceHandler         = (*delegationConnectHandler)(nil)
	_ genconnect.GDPRServiceHandler               = (*gdprConnectHandler)(nil)
	_ genconnect.IdentityServiceHandler           = (*identConnectHandler)(nil)
	_ genconnect.InstallationServiceHandler       = (*installationConnectHandler)(nil)
	_ genconnect.IntrospectionServiceHandler      = (*introspectionConnectHandler)(nil)
	_ genconnect.InvitationServiceHandler         = (*invitationConnectHandler)(nil)
	_ genconnect.MFAServiceHandler                = (*mfaConnectHandler)(nil)
	_ genconnect.ModuleCapabilitiesServiceHandler = (*moduleCapabilitiesConnectHandler)(nil)
	_ genconnect.NotificationServiceHandler       = (*notificationConnectHandler)(nil)
	_ genconnect.OnboardingServiceHandler         = (*onboardingConnectHandler)(nil)
	_ genconnect.OrganizationServiceHandler       = (*orgConnectHandler)(nil)
	_ genconnect.PermissionServiceHandler         = (*permConnectHandler)(nil)
	_ genconnect.PlatformAdminServiceHandler      = (*platformAdminConnectHandler)(nil)
	_ genconnect.PrincipalServiceHandler          = (*principalConnectHandler)(nil)
	_ genconnect.ResourceFollowServiceHandler     = (*resourceFollowConnectHandler)(nil)
	_ genconnect.SSOAdminServiceHandler           = (*ssoAdminConnectHandler)(nil)
	_ genconnect.SolutionRegistryServiceHandler   = (*solutionRegistryConnectHandler)(nil)
	_ genconnect.TeamServiceHandler               = (*teamConnectHandler)(nil)
	_ genconnect.UsageServiceHandler              = (*usageConnectHandler)(nil)
	_ genconnect.UserServiceHandler               = (*userConnectHandler)(nil)
	_ genconnect.UserSettingsServiceHandler       = (*userSettingsConnectHandler)(nil)
	_ genconnect.WaitlistServiceHandler           = (*waitlistConnectHandler)(nil)
	_ genconnect.WebhookServiceHandler            = (*webhookConnectHandler)(nil)
	_ genconnect.WorkContextServiceHandler        = (*workContextConnectHandler)(nil)
)

// registerCatalogConnectServices registers every catalog service on one mux.
// Exact procedure paths remain owned by protoc-gen-connect-go.
func registerCatalogConnectServices(mux *http.ServeMux, server *ConnectServer, options ...connect.HandlerOption) {
	mux.Handle(genconnect.NewAPIKeyServiceHandler(&apiKeyConnectHandler{inner: server.grpc.APIKey}, options...))
	mux.Handle(genconnect.NewAccessibleScopeServiceHandler(&accessibleScopeConnectHandler{inner: AccessibleScopeSingleton()}, options...))
	mux.Handle(genconnect.NewAuditServiceHandler(&auditConnectHandler{inner: server.grpc.Audit}, options...))
	mux.Handle(genconnect.NewAuthServiceHandler(&authConnectHandler{inner: server.grpc.Auth}, options...))
	mux.Handle(genconnect.NewBillingServiceHandler(&billingConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewConsentServiceHandler(&consentConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewDashboardServiceHandler(&dashboardConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewDatasourceServiceHandler(&datasourceConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewDelegationServiceHandler(&delegationConnectHandler{inner: DelegationSingleton()}, options...))
	mux.Handle(genconnect.NewGDPRServiceHandler(&gdprConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewIdentityServiceHandler(&identConnectHandler{inner: server.grpc.Ident}, options...))
	mux.Handle(genconnect.NewInstallationServiceHandler(&installationConnectHandler{inner: InstallationSingleton()}, options...))
	mux.Handle(genconnect.NewIntrospectionServiceHandler(&introspectionConnectHandler{inner: server.grpc.Introspection}, options...))
	mux.Handle(genconnect.NewInvitationServiceHandler(&invitationConnectHandler{inner: server.grpc.Invitation}, options...))
	mux.Handle(genconnect.NewMFAServiceHandler(&mfaConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewModuleCapabilitiesServiceHandler(&moduleCapabilitiesConnectHandler{inner: ModuleCapabilitiesSingleton()}, options...))
	mux.Handle(genconnect.NewNotificationServiceHandler(&notificationConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewOnboardingServiceHandler(&onboardingConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewOrganizationServiceHandler(&orgConnectHandler{inner: server.grpc.Org}, options...))
	mux.Handle(genconnect.NewPermissionServiceHandler(&permConnectHandler{inner: server.grpc.Perm}, options...))
	mux.Handle(genconnect.NewPlatformAdminServiceHandler(&platformAdminConnectHandler{inner: server.grpc.PlatformAdmin}, options...))
	mux.Handle(genconnect.NewPrincipalServiceHandler(&principalConnectHandler{inner: PrincipalSingleton()}, options...))
	mux.Handle(genconnect.NewResourceFollowServiceHandler(&resourceFollowConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewSSOAdminServiceHandler(&ssoAdminConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewSolutionRegistryServiceHandler(&solutionRegistryConnectHandler{inner: SolutionRegistrySingleton()}, options...))
	mux.Handle(genconnect.NewTeamServiceHandler(&teamConnectHandler{inner: server.grpc.Team}, options...))
	mux.Handle(genconnect.NewUsageServiceHandler(&usageConnectHandler{inner: UsageSingleton()}, options...))
	mux.Handle(genconnect.NewUserServiceHandler(&userConnectHandler{inner: server.grpc.User}, options...))
	mux.Handle(genconnect.NewUserSettingsServiceHandler(&userSettingsConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewWaitlistServiceHandler(&waitlistConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewWebhookServiceHandler(&webhookConnectHandler{svc: server.service}, options...))
	mux.Handle(genconnect.NewWorkContextServiceHandler(&workContextConnectHandler{inner: WorkContextSingleton()}, options...))
}
