// Code generated by cmd/connect-registration from generated/service-catalog.json and connect_bindings.yaml. DO NOT EDIT.

package adapters

import (
	"google.golang.org/grpc"

	gen "accounts/pkg/gen/saas/accounts/v1"
)

// registerCatalogGRPCServices registers every catalog service backed by a
// native gRPC implementation. Connect-native business handlers are served by
// the catalog-complete Connect listener and are intentionally omitted here.
func registerCatalogGRPCServices(registrar grpc.ServiceRegistrar, server *GrpcServer) {
	gen.RegisterAPIKeyServiceServer(registrar, server.APIKey)
	gen.RegisterAccessibleScopeServiceServer(registrar, AccessibleScopeSingleton())
	gen.RegisterAuditServiceServer(registrar, server.Audit)
	gen.RegisterAuthServiceServer(registrar, server.Auth)
	gen.RegisterDelegationServiceServer(registrar, DelegationSingleton())
	gen.RegisterIdentityServiceServer(registrar, server.Ident)
	gen.RegisterInstallationServiceServer(registrar, InstallationSingleton())
	gen.RegisterIntrospectionServiceServer(registrar, server.Introspection)
	gen.RegisterInvitationServiceServer(registrar, server.Invitation)
	gen.RegisterMFAServiceServer(registrar, server.MFA)
	gen.RegisterModuleCapabilitiesServiceServer(registrar, ModuleCapabilitiesSingleton())
	gen.RegisterOrganizationServiceServer(registrar, server.Org)
	gen.RegisterPermissionServiceServer(registrar, server.Perm)
	gen.RegisterPlatformAdminServiceServer(registrar, server.PlatformAdmin)
	gen.RegisterPrincipalServiceServer(registrar, PrincipalSingleton())
	gen.RegisterSolutionRegistryServiceServer(registrar, SolutionRegistrySingleton())
	gen.RegisterTeamServiceServer(registrar, server.Team)
	gen.RegisterUsageServiceServer(registrar, UsageSingleton())
	gen.RegisterUserServiceServer(registrar, server.User)
	gen.RegisterWorkContextServiceServer(registrar, WorkContextSingleton())
}

var catalogGRPCServiceNames = []string{
	"saas.accounts.v1.APIKeyService",
	"saas.accounts.v1.AccessibleScopeService",
	"saas.accounts.v1.AuditService",
	"saas.accounts.v1.AuthService",
	"saas.accounts.v1.DelegationService",
	"saas.accounts.v1.IdentityService",
	"saas.accounts.v1.InstallationService",
	"saas.accounts.v1.IntrospectionService",
	"saas.accounts.v1.InvitationService",
	"saas.accounts.v1.MFAService",
	"saas.accounts.v1.ModuleCapabilitiesService",
	"saas.accounts.v1.OrganizationService",
	"saas.accounts.v1.PermissionService",
	"saas.accounts.v1.PlatformAdminService",
	"saas.accounts.v1.PrincipalService",
	"saas.accounts.v1.SolutionRegistryService",
	"saas.accounts.v1.TeamService",
	"saas.accounts.v1.UsageService",
	"saas.accounts.v1.UserService",
	"saas.accounts.v1.WorkContextService",
}

var catalogConnectOnlyServiceNames = []string{
	"saas.accounts.v1.BillingService",
	"saas.accounts.v1.ConsentService",
	"saas.accounts.v1.DashboardService",
	"saas.accounts.v1.DatasourceService",
	"saas.accounts.v1.GDPRService",
	"saas.accounts.v1.NotificationService",
	"saas.accounts.v1.OnboardingService",
	"saas.accounts.v1.ResourceFollowService",
	"saas.accounts.v1.SSOAdminService",
	"saas.accounts.v1.UserSettingsService",
	"saas.accounts.v1.WaitlistService",
	"saas.accounts.v1.WebhookService",
}
