// Code generated by cmd/rest-surface from generated/rest-surface.json and rest_bindings.yaml. DO NOT EDIT.

package adapters

import (
	"context"
	"fmt"
	"net/http"
	"regexp"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"

	gen "accounts/pkg/gen/saas/accounts/v1"
	"accounts/plugins"
)

func registerCatalogRESTHandlers(ctx context.Context, mux *runtime.ServeMux, endpoint string, options []grpc.DialOption) error {
	if err := gen.RegisterAPIKeyServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service APIKeyService: %w", err)
	}
	if err := gen.RegisterAccessibleScopeServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service AccessibleScopeService: %w", err)
	}
	if err := gen.RegisterAuditServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service AuditService: %w", err)
	}
	if err := gen.RegisterAuthServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service AuthService: %w", err)
	}
	if err := gen.RegisterBillingServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service BillingService: %w", err)
	}
	if err := gen.RegisterConsentServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service ConsentService: %w", err)
	}
	if err := gen.RegisterGDPRServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service GDPRService: %w", err)
	}
	if err := gen.RegisterIntrospectionServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service IntrospectionService: %w", err)
	}
	if err := gen.RegisterInvitationServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service InvitationService: %w", err)
	}
	if err := gen.RegisterMFAServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service MFAService: %w", err)
	}
	if err := gen.RegisterNotificationServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service NotificationService: %w", err)
	}
	if err := gen.RegisterOnboardingServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service OnboardingService: %w", err)
	}
	if err := gen.RegisterOrganizationServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service OrganizationService: %w", err)
	}
	if err := gen.RegisterPermissionServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service PermissionService: %w", err)
	}
	if err := gen.RegisterPlatformAdminServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service PlatformAdminService: %w", err)
	}
	if err := gen.RegisterResourceFollowServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service ResourceFollowService: %w", err)
	}
	if err := gen.RegisterSSOAdminServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service SSOAdminService: %w", err)
	}
	if err := gen.RegisterTeamServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service TeamService: %w", err)
	}
	if err := gen.RegisterUsageServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service UsageService: %w", err)
	}
	if err := gen.RegisterUserServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service UserService: %w", err)
	}
	if err := gen.RegisterUserSettingsServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service UserSettingsService: %w", err)
	}
	if err := gen.RegisterWaitlistServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service WaitlistService: %w", err)
	}
	if err := gen.RegisterWebhookServiceHandlerFromEndpoint(ctx, mux, endpoint, options); err != nil {
		return fmt.Errorf("register generated REST service WebhookService: %w", err)
	}
	seenPluginPermissions := false
	for _, plugin := range plugins.All() {
		switch plugin.Name() {
		case "permissions":
			if seenPluginPermissions {
				return fmt.Errorf("REST plugin permissions is registered more than once")
			}
			if err := plugin.RegisterREST(ctx, mux, endpoint, options); err != nil {
				return fmt.Errorf("register REST plugin permissions: %w", err)
			}
			seenPluginPermissions = true
		}
	}
	if !seenPluginPermissions {
		return fmt.Errorf("required REST plugin permissions is not registered")
	}
	return nil
}

var catalogRESTExactRoutes = map[string]struct{}{
	"DELETE /v1/record-shares":                 {},
	"DELETE /v1/role-assignments":              {},
	"DELETE /v1/scope-grants":                  {},
	"GET /v1/.well-known/service-info":         {},
	"GET /v1/accessible-scopes":                {},
	"GET /v1/acquisition":                      {},
	"GET /v1/api-keys":                         {},
	"GET /v1/audit-event-types":                {},
	"GET /v1/audit-log":                        {},
	"GET /v1/audit-log:aggregate":              {},
	"GET /v1/auth/.well-known/jwks.json":       {},
	"GET /v1/collection-access":                {},
	"GET /v1/consent/status":                   {},
	"GET /v1/delegations:pending":              {},
	"GET /v1/invitations":                      {},
	"GET /v1/mfa/devices":                      {},
	"GET /v1/notifications":                    {},
	"GET /v1/notifications/unread-count":       {},
	"GET /v1/organizations":                    {},
	"GET /v1/platform/admins":                  {},
	"GET /v1/platform/events/operations":       {},
	"GET /v1/platform/events/subscriptions":    {},
	"GET /v1/platform/feature-flags":           {},
	"GET /v1/platform/jobs":                    {},
	"GET /v1/platform/jobs/operations":         {},
	"GET /v1/platform/sessions":                {},
	"GET /v1/platform/users":                   {},
	"GET /v1/platform/waitlist":                {},
	"GET /v1/principals":                       {},
	"GET /v1/public/plans":                     {},
	"GET /v1/record-shares":                    {},
	"GET /v1/role-assignments":                 {},
	"GET /v1/roles":                            {},
	"GET /v1/user/settings":                    {},
	"GET /v1/users":                            {},
	"GET /v1/users/self":                       {},
	"GET /v1/users:byEmail":                    {},
	"GET /v1/users:findByIdentity":             {},
	"GET /v1/version":                          {},
	"GET /v1/webhooks":                         {},
	"POST /v1/api-keys":                        {},
	"POST /v1/audit-log:export":                {},
	"POST /v1/auth/authenticate":               {},
	"POST /v1/auth/logout":                     {},
	"POST /v1/auth/mfa/complete":               {},
	"POST /v1/auth/mfa/webauthn/begin":         {},
	"POST /v1/auth/mfa/webauthn/complete":      {},
	"POST /v1/auth/oauth/begin":                {},
	"POST /v1/auth/refresh":                    {},
	"POST /v1/auth/switch-organization":        {},
	"POST /v1/billing/connect/portal":          {},
	"POST /v1/consent/terms":                   {},
	"POST /v1/delegations":                     {},
	"POST /v1/gdpr/delete":                     {},
	"POST /v1/gdpr/export":                     {},
	"POST /v1/installations":                   {},
	"POST /v1/invitations":                     {},
	"POST /v1/invitations:accept":              {},
	"POST /v1/invitations:inspect":             {},
	"POST /v1/invitations:inspect-id":          {},
	"POST /v1/mfa/backup-codes":                {},
	"POST /v1/mfa/totp/setup":                  {},
	"POST /v1/mfa/totp/verify":                 {},
	"POST /v1/mfa/webauthn/register/begin":     {},
	"POST /v1/mfa/webauthn/register/finish":    {},
	"POST /v1/notifications:read-all":          {},
	"POST /v1/organizations":                   {},
	"POST /v1/platform/admins":                 {},
	"POST /v1/principals:agent":                {},
	"POST /v1/record-shares":                   {},
	"POST /v1/resource-follows":                {},
	"POST /v1/resource-follows:unfollow":       {},
	"POST /v1/role-assignments":                {},
	"POST /v1/roles":                           {},
	"POST /v1/scope-grants":                    {},
	"POST /v1/scope-nodes":                     {},
	"POST /v1/sso/disable":                     {},
	"POST /v1/sso/setup":                       {},
	"POST /v1/user/settings":                   {},
	"POST /v1/users":                           {},
	"POST /v1/waitlist":                        {},
	"POST /v1/waitlist:verify":                 {},
	"POST /v1/webhooks":                        {},
	"POST /v1/work-contexts:child-session":     {},
	"POST /v1/work-contexts:exchange-audience": {},
	"POST /v1/work-contexts:renew":             {},
	"POST /v1/work-contexts:root-session":      {},
	"POST /v1/work-contexts:task":              {},
	"PUT /v1/consent/preferences":              {},
}

type catalogRESTTemplateRoute struct {
	method string
	path   *regexp.Regexp
}

var catalogRESTTemplateRoutes = []catalogRESTTemplateRoute{
	{method: "DELETE", path: regexp.MustCompile("^/v1/api-keys/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/invitations/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/mfa/devices/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/notifications/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/organizations/[^/]+/members/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/platform/admins/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/platform/sessions/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/roles/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/teams/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/teams/[^/]+/members/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/users/[^/]+$")},
	{method: "DELETE", path: regexp.MustCompile("^/v1/webhooks/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/billing/invoices/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/delegations/[^/]+:wait$")},
	{method: "GET", path: regexp.MustCompile("^/v1/gdpr/delete/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/gdpr/export/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/installations/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/generic-settings$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/members$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/settings$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/teams$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/onboarding$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/usage$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/usage/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/organizations/[^/]+/usage/[^/]+/history$")},
	{method: "GET", path: regexp.MustCompile("^/v1/platform/jobs/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/platform/organizations/[^/]+/entitlements$")},
	{method: "GET", path: regexp.MustCompile("^/v1/sso/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/teams/[^/]+/members$")},
	{method: "GET", path: regexp.MustCompile("^/v1/users/[^/]+/identities$")},
	{method: "GET", path: regexp.MustCompile("^/v1/users/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/webhooks/deliveries/[^/]+$")},
	{method: "GET", path: regexp.MustCompile("^/v1/webhooks/[^/]+/deliveries$")},
	{method: "PATCH", path: regexp.MustCompile("^/v1/teams/[^/]+$")},
	{method: "PATCH", path: regexp.MustCompile("^/v1/users/[^/]+$")},
	{method: "POST", path: regexp.MustCompile("^/v1/delegations/[^/]+:decide$")},
	{method: "POST", path: regexp.MustCompile("^/v1/installations/[^/]+:transferOwnership$")},
	{method: "POST", path: regexp.MustCompile("^/v1/installations/[^/]+:uninstall$")},
	{method: "POST", path: regexp.MustCompile("^/v1/invitations/[^/]+:resend$")},
	{method: "POST", path: regexp.MustCompile("^/v1/notifications/[^/]+:read$")},
	{method: "POST", path: regexp.MustCompile("^/v1/organizations/[^/]+/generic-settings$")},
	{method: "POST", path: regexp.MustCompile("^/v1/organizations/[^/]+/members$")},
	{method: "POST", path: regexp.MustCompile("^/v1/organizations/[^/]+/teams$")},
	{method: "POST", path: regexp.MustCompile("^/v1/organizations/[^/]+/onboarding/[^/]+:complete$")},
	{method: "POST", path: regexp.MustCompile("^/v1/organizations/[^/]+/onboarding/[^/]+:skip$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/jobs/[^/]+:replay$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/organizations/[^/]+/entitlements$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/users/[^/]+:impersonate$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/users/[^/]+:suspend$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/users/[^/]+:unsuspend$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/waitlist/[^/]+:invite$")},
	{method: "POST", path: regexp.MustCompile("^/v1/platform/waitlist/[^/]+:review$")},
	{method: "POST", path: regexp.MustCompile("^/v1/principals/[^/]+:revoke$")},
	{method: "POST", path: regexp.MustCompile("^/v1/teams/[^/]+/members$")},
	{method: "POST", path: regexp.MustCompile("^/v1/users/[^/]+/identities$")},
	{method: "POST", path: regexp.MustCompile("^/v1/webhooks/deliveries/[^/]+:replay$")},
	{method: "POST", path: regexp.MustCompile("^/v1/webhooks/[^/]+:rotateSecret$")},
	{method: "POST", path: regexp.MustCompile("^/v1/webhooks/[^/]+:test$")},
	{method: "PUT", path: regexp.MustCompile("^/v1/organizations/[^/]+/settings$")},
	{method: "PUT", path: regexp.MustCompile("^/v1/platform/feature-flags/[^/]+$")},
}

func catalogRESTRouteAllowed(method, path string) bool {
	if _, ok := catalogRESTExactRoutes[method+" "+path]; ok {
		return true
	}
	for _, route := range catalogRESTTemplateRoutes {
		if route.method == method && route.path.MatchString(path) {
			return true
		}
	}
	return false
}

func catalogRESTHandler(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
		if !catalogRESTRouteAllowed(request.Method, request.URL.Path) {
			http.NotFound(w, request)
			return
		}
		next.ServeHTTP(w, request)
	})
}
